# Generated by Django 5.1.3 on 2024-11-15 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="s_phone",
        ),
    ]
