# Generated by Django 5.1.3 on 2024-11-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_remove_student_s_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="s_major",
            new_name="major",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="s_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="s_age",
        ),
        migrations.RemoveField(
            model_name="student",
            name="s_gender",
        ),
        migrations.RemoveField(
            model_name="student",
            name="s_grade",
        ),
        migrations.AddField(
            model_name="student",
            name="age",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(default="M", max_length=1),
        ),
        migrations.AddField(
            model_name="student",
            name="grade",
            field=models.IntegerField(default=1),
        ),
    ]
